### ISSUE TITLE
Update usage instructions

### ISSUE THREAD

**Issue by GauthamAsir** [Welltested-AI/welltested#3]
Instructions are unclear and confusing. According to current Instructions from README it says to use this command `welltested generate build` but it throws error saying `Could not find a subcommand named "build" for "welltested generate".` and when help command is used it says `generate, build` these two sub commands are available but when `build` sub command is executed it says only `unit` sub command is available

**Comment by samyakkkk** [comment]
Thanks for noting this @GauthamAsir. We will be pushing the fix shortly.
