### ISSUE TITLE
Sign-up seems to be broken

### ISSUE THREAD

**Issue by ReCREWt-Fabi** [Welltested-AI/welltested#8]
Hi there,

We'd like to try out Welltested, but when trying to sign-up for the Free Plan, i can't create an account.

The console shows the following error: 
![Bildschirmfoto 2024-03-08 um 14 20 27](https://github.com/Welltested-AI/welltested/assets/52889595/39cd47c2-109f-4165-adcc-631accc9e7f4)

Could you help me there?

**Comment by samyakkkk** [comment]
Hi @ReCREWt-Fabi, thanks for reporting this. The issue should be resolved now. 

Please let us know if not. Thanks.

**Comment by ReCREWt-Fabi** [comment]
Hi @samyakkkk, thanks it worked!

**Comment by neiljaywarner** [comment]
@ReCREWt-Fabi  plz close issue so the repo "Seems" better upon quick glance + @samyakkkk

**Comment by samyakkkk** [comment]
thanks @neiljaywarner. closing.
